CREATE SCHEMA AIRPORT_MANAGEMENT_SYSTEM;
USE AIRPORT_MANAGEMENT_SYSTEM;

CREATE TABLE COMPANIES
(
    ID         INT          NOT NULL AUTO_INCREMENT,
    NAME       VARCHAR(100) NOT NULL,
    FOUND_DATE DATE         NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE ADDRESS
(
    ID      INT          NOT NULL AUTO_INCREMENT,
    COUNTRY VARCHAR(100) NOT NULL,
    CITY    VARCHAR(100) NOT NULL UNIQUE,
    PRIMARY KEY (ID)
);

CREATE TABLE PASSENGERS
(
    ID         INT          NOT NULL AUTO_INCREMENT,
    NAME       VARCHAR(100) NOT NULL,
    PHONE      VARCHAR(100) NOT NULL UNIQUE,
    ADDRESS_ID INT          NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS (ID)
);

CREATE TABLE TRIP
(
    ID         INT          NOT NULL AUTO_INCREMENT,
    COMPANY_ID INT          NOT NULL,
    TIME_IN    TIMESTAMP    NOT NULL,
    TIME_OUT   TIMESTAMP    NOT NULL,
    CITY_FROM  VARCHAR(100) NOT NULL,
    CITY_TOO   VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (COMPANY_ID) REFERENCES COMPANIES (ID)
);

CREATE TABLE PASSENGER_TRIPS
(
    ID           INT NOT NULL AUTO_INCREMENT,
    PASSENGER_ID INT NOT NULL,
    TRIP_ID      INT NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (PASSENGER_ID) REFERENCES PASSENGERS (ID),
    FOREIGN KEY (TRIP_ID) REFERENCES TRIP (ID)
);